---
- name: Ensure Docker is installed and running
  hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

- name: Transfer project files to production node
  hosts: development
  tasks:
    - name: Copy best_model.pkl to control node
      fetch:
        src: /home/ubuntu/DEII-Project3/best_model.pkl
        dest: /tmp/best_model.pkl
        flat: yes

- name: Prepare directory structure on production node
  hosts: production
  become: true
  tasks:
    - name: Create project directory
      file:
        path: /home/ubuntu/DEII-Project3
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

- name: Copy project files to production node
  hosts: production
  tasks:
    - name: Copy best_model.pkl from control node to production node
      copy:
        src: /tmp/best_model.pkl
        dest: /home/ubuntu/DEII-Project3/best_model.pkl

- name: Build and run Docker container on production server
  hosts: production
  become: true
  tasks:
    - name: Log in to Docker Hub
      shell: echo "P@kistan1234" | docker login -u "zeeshanm96" --password-stdin

    - name: Build Docker image
      command: docker build -t my-github-project:latest /home/ubuntu/DEII-Project3

    - name: Run container with best model
      docker_container:
        name: github_project
        image: my-github-project:latest
        state: started
        ports:
          - "8000:8000"
        restart_policy: always